version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: egp-backend
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"

  mysql:
    container_name: egp-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: egp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports: 
      - "8081:3306"

  phpmyadmin:
    container_name: egp-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "8082:80"
    environment: 
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - /sessions
